<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        spacing: 20
        padding: 50

        Button:
            text: "Helllo world"
        
        Button:
            text: "Helllo Rocky"

        Button:
            text: "Helllo Inu"
            pos_hint: {'center_x':0.5}
            size_hint: (0.2,1)
            #width: 200
            #height: 50
