<MyLayout>
    BoxLayout:
        orientation:"vertical"
        size: root.width, root.height

        Carousel:
            direction: "right"

            Image:
                source:"assets/goku.jpeg"
            # AsyncImage: 
                # source: ""

            Image:
                source:"assets/luffy.jpeg"

            Image:
                source:"assets/vegeta.jpeg"