<MyLayout>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        Label:
            id: click_label
            text: "text"
            font_size: 32

        Spinner:
            id: spinner_id
            text: "Favorite food"
            values: ["Rose Milk" , "Cake" , "Milk Shake"]
            on_text: root.spinner_clicked(spinner_id.text)

        Label:
            text: ''
